theme: "just-the-docs"

title: Trifork Befordring
description: >
  Website some indeholder dokumentation for brug af Trifork Befordring.
lang: da-DK
baseurl: "/trifork-dash-docs-website" 
url: "https://trifork.github.io" 

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
