remote_theme: pmarsceill/just-the-docs

title: Trifork Befordring
description: >
  Website som indeholder dokumentation for brug af Trifork Befordring.
lang: da-DK
baseurl: "/" 
url: "https://befordring.dash.trifork.com" 

# Aux links for the upper right navigation
aux_links:
  "Trifork":
    - "//trifork.com"

footer_content: Copyright &copy; 2021 Trifork A/S.
